services:
  backend:
    build:
      context: .
      dockerfile: app/backend/DockerfileGit
    ports:
      - "8080:8080"
    environment:
      # To avoid some Gin debugging lines.
      - GIN_MODE=release
      - PORT=8080  # This mimics what Cloud Run does
  frontend:
    build:
      context: .
      dockerfile: app/frontend/DockerfileGit
    environment:
      - PORT=80
      - BACKEND_URL=http://backend:8080
    ports:
      - "8081:80"
    depends_on:
      - backend # The frontend might depend on the backend