services:
  backend:
    build:
      context: .
      dockerfile: app/backend/DockerfileGit
    ports:
      - "8080:8080"
    environment:
      # To avoid some Gin debugging lines.
      - GIN_MODE=release
  frontend:
    build:
      context: .
      dockerfile: app/frontend/DockerfileGit
    ports:
      - "8081:80"
    depends_on:
      - backend # The frontend might depend on the backend