services:
  backend:
    build: 
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - PORT=8080  # This mimics what Cloud Run does

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    environment:
      - PORT=80
      - BACKEND_URL=http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - backend # The frontend might depend on the backend